### ISSUE TITLE
Prevent that an element in the background can get the focus by tabbing 

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/ax-details-layer-widget#17]
The widget should prevent that the user can focus an element in the background by tabbing

**Comment by x1B** [comment]
@jonaswjs sure that this issue is still open. According to the changelog, you already merged it. Maybe waffle reopened the issue?

**Comment by jonaswjs** [comment]
Fixed on `master` (`v1.2.0`) and on release-1.1.x (`v1.1.1`).
