### ISSUE TITLE
v1.x: jQuery is implicitly expected to be available instead of jqLite

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/ax-details-layer-widget#27]
When checking for tabbable nodes jQuery API is used instead of jqLite API (https://github.com/LaxarJS/ax-details-layer-widget/blob/release-1.4.x/ax-details-layer-widget.js#L224). `each()` is only available in jQuery and not in elements wrapped by jqLite. Hence, either remove the use of the jQuery / jqLite API completely as it is the case for the v2.x version, or use `angular.forEach` to iterate over the nodes.
The error was:
```
ax-details-layer-widget.js:224 Uncaught TypeError: element.find(...).each is not a function
at findFirstOrLast (ax-details-layer-widget.js:224)
at HTMLDocument.checkFocus (ax-details-layer-widget.js:207)
```

**Comment by jonaswjs** [comment]
Fixed on `release-1.4.x` (`v1.4.3`).
